management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      enabled: true
      group:
        details:
          show-details: "always"
    info:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

springdoc:
  show-actuator: true
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

logging:
  level:
    com.example.backend: DEBUG

spring:
  security:
    user:
      name: user
      password: password
    roles: USER

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console: # http://localhost:8080/h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect